/*
 * scripts/embed.c - A simple tool to embed assets into C code.
 * Replaces the need for sh, xxd, and stat in the build process.
 */

#include <stdio.h>
#include <sys/stat.h>
#include <time.h>

#ifdef _WIN32
#define STAT_STRUCT struct _stat
#define STAT_FUNC _stat
#else
#define STAT_STRUCT struct stat
#define STAT_FUNC stat
#endif

typedef struct {
  const char *path;
  const char *name;
} Asset;

Asset g_assets[] = {
    {"assets/fonts/JetBrainsMono-Regular.ttf", "asset_font_regular"},
    {"assets/workbench_icon.png", "asset_icon_png"}};

int main(int argc, char **argv) {
  const char *output_c = "src/core/assets_embedded.c";
  const char *output_h = "src/core/assets_embedded.h";
  int num_assets = sizeof(g_assets) / sizeof(g_assets[0]);

  /* 1. Check if update is needed */
  STAT_STRUCT out_stat;
  int needs_update = 0;
  if (STAT_FUNC(output_c, &out_stat) != 0 ||
      STAT_FUNC(output_h, &out_stat) != 0) {
    needs_update = 1;
  } else {
    time_t out_time = out_stat.st_mtime;
    for (int i = 0; i < num_assets; i++) {
      STAT_STRUCT in_stat;
      if (STAT_FUNC(g_assets[i].path, &in_stat) == 0) {
        if (in_stat.st_mtime > out_time) {
          needs_update = 1;
          break;
        }
      }
    }
  }

  if (!needs_update) {
    printf("Embedded assets are up to date.\n");
    return 0;
  }

  /* 2. Generate Files */
  FILE *fc = fopen(output_c, "w");
  FILE *fh = fopen(output_h, "w");
  if (!fc || !fh) {
    fprintf(stderr, "Error: Could not open output files for writing.\n");
    return 1;
  }

  fprintf(fc, "/* Automatically generated by scripts/embed.c */\n");
  fprintf(fc, "#include \"assets_embedded.h\"\n\n");

  fprintf(fh, "/* Automatically generated by scripts/embed.c */\n");
  fprintf(fh, "#ifndef ASSETS_EMBEDDED_H\n");
  fprintf(fh, "#define ASSETS_EMBEDDED_H\n");
  fprintf(fh, "#include \"types.h\"\n\n");

  for (int i = 0; i < num_assets; i++) {
    FILE *in = fopen(g_assets[i].path, "rb");
    if (!in) {
      fprintf(stderr, "Warning: Could not open asset %s\n", g_assets[i].path);
      continue;
    }

    fseek(in, 0, SEEK_END);
    long size = ftell(in);
    fseek(in, 0, SEEK_SET);

    fprintf(fc, "unsigned char %s_data[] = {\n    ", g_assets[i].name);
    for (long j = 0; j < size; j++) {
      fprintf(fc, "0x%02x%s", fgetc(in), (j == size - 1) ? "" : ", ");
      if ((j + 1) % 12 == 0)
        fprintf(fc, "\n    ");
    }
    fprintf(fc, "\n};\n");
    fprintf(fc, "unsigned int %s_size = %ld;\n\n", g_assets[i].name, size);

    fprintf(fh, "extern unsigned char %s_data[];\n", g_assets[i].name);
    fprintf(fh, "extern unsigned int %s_size;\n", g_assets[i].name);

    fclose(in);
  }

  fprintf(fh, "\n#endif\n");

  fclose(fc);
  fclose(fh);

  printf("Assets embedded successfully.\n");
  return 0;
}
